abdul_homepage:
    path:       /
    defaults:   { _controller: AbdulBundle:Default:index }

abdul_save_product:
    path:       /save
    defaults:   { _controller: AbdulBundle:Product:save }

abdul_get_product:
    path:       /get/{productId}
    defaults:
        _controller: AbdulBundle:Product:getByPrimaryKey
        requirements:
            productId: \d+

abdul_find_product:
    path:       /find/{price}
    defaults:
        _controller: AbdulBundle:Product:find

abdul_update_product:
    path:       /update/{id}/{price}
    defaults:
        _controller: AbdulBundle:Product:update
        requirements:
            id: \d+
            price: "[0-9\.]+"

abdul_delete_product:
    path:       /delete/{productId}
    defaults:
        _controller: AbdulBundle:Product:delete
        requirements:
            productId: \d+

abdul_createquery_product:
    path:       /create-query/{minPrice}
    defaults:
        _controller: AbdulBundle:Product:createQuery

abdul_querybuilder_product:
    path:       /query-builder/{minPrice}
    defaults:
        _controller: AbdulBundle:Product:queryBuilder

abdul_customrepofunction_product:
    path:       /custom-repo-function
    defaults:
        _controller: AbdulBundle:Product:customRepoFunction