<?php

namespace AbdulBundle\Repository;

/**
 * CommunicationPreferencesNewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunicationPreferencesNewRepository extends \Doctrine\ORM\EntityRepository
{
}
